language: go

go:
  - "1.18"
  - release
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -test.v
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)